export const BUSINESS_PHONE_DISPLAY =
  process.env.NEXT_PUBLIC_BUSINESS_PHONE_DISPLAY || "+1 (647) 995-6665";

export const BUSINESS_PHONE_RAW =
  process.env.NEXT_PUBLIC_BUSINESS_PHONE || "+16479956665";

export const BUSINESS_PHONE_TEL = `tel:${BUSINESS_PHONE_RAW}`;
