export const BUSINESS_PHONE_DISPLAY =
  process.env.NEXT_PUBLIC_BUSINESS_PHONE_DISPLAY || "(800) 555-TIRE (8473)";

export const BUSINESS_PHONE_RAW =
  process.env.NEXT_PUBLIC_BUSINESS_PHONE || "+18005558473";
